import sharp from "sharp";
import { readdirSync, mkdirSync, writeFileSync } from "fs";
import { join, extname, basename, resolve } from "path";

const IMAGE_EXTS = new Set([".webp", ".jpg", ".jpeg", ".png"]);

const SKIP_KEYS = new Set([
  "favicon",
  "opengraph",
  "taurus-logo",
  "robots",
  "farm-vrt-poster",
]);

const websiteDir = resolve(import.meta.dirname, "../../artifacts/taurus-website");
const publicDir = join(websiteDir, "public");
const generatedDir = join(websiteDir, "src/generated");
const outFile = join(generatedDir, "thumbnails.ts");

const THUMB_WIDTH = 20;
const THUMB_HEIGHT = 15;

async function main(): Promise<void> {
  const files = readdirSync(publicDir).filter((f) =>
    IMAGE_EXTS.has(extname(f).toLowerCase()),
  );

  const entries: Array<[string, string]> = [];

  for (const file of files.sort()) {
    const key = basename(file, extname(file));
    if (SKIP_KEYS.has(key)) continue;

    const imgPath = join(publicDir, file);
    let b64: string;
    try {
      const buf = await sharp(imgPath)
        .resize(THUMB_WIDTH, THUMB_HEIGHT, { fit: "cover" })
        .jpeg({ quality: 60 })
        .toBuffer();
      b64 = `data:image/jpeg;base64,${buf.toString("base64")}`;
    } catch (err) {
      console.warn(`  skip ${file}: ${(err as Error).message}`);
      continue;
    }

    entries.push([key, b64]);
    console.log(`  ✓ ${key}`);
  }

  mkdirSync(generatedDir, { recursive: true });

  const lines: string[] = [
    "/* Auto-generated by scripts/src/gen-thumbnails.ts — do not edit by hand. */",
    "/* Run: pnpm --filter @workspace/taurus-website run codegen                */",
    "",
    "export const THUMBNAILS: Record<string, string> = {",
    ...entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
    "};",
    "",
  ];

  writeFileSync(outFile, lines.join("\n"), "utf8");
  console.log(`\nWrote ${entries.length} thumbnails → ${outFile}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
